update django versions
maykinmedia/django-loose-fk pull request #26
Opened 2023-07-05 14:06 UTC by annashamray

Note:
I tried to update to Django 4.1 but the tests failed, it will require some additional time, effort and separate issue.

2023-07-05 15:09 UTC, sergei-maertens commented on setup.cfg
> +    coreapi
I don't understand why this is needed - isn't that part of drf?

2023-07-05 15:10 UTC, sergei-maertens requested changes, later dismissed

2023-07-05 15:10 UTC, sergei-maertens commented on testapp/settings.py
> +DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
this actually needs to be set in the  `AppConfig` - the models themselves when installed as part of OZ don't use this setting so you'll end up with the reverse migration again.

2023-07-05 15:18 UTC, annashamray commented on testapp/settings.py
> +DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
@sergei-maertens But it's only a part of the test app. The lib itself doesn't have models and model-specific settings 
I don't want to include it into  `AppConfig` for this reason

2023-07-05 15:27 UTC, annashamray commented on setup.cfg
> +    coreapi
It looks like DRF wants to drop its support in the future versions
But it has assertion for coreapi 
https://github.com/encode/django-rest-framework/blob/4f7e9ed3bbb0fb3567884ef4e3d340bc2f77bc68/rest_framework/filters.py#L33

2023-07-13 16:21 UTC, joeribekker approved these changes

2023-07-14 10:48 UTC, sergei-maertens commented on testapp/settings.py
> +DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
yeah, my bad!

2023-07-14 10:48 UTC, sergei-maertens approved these changes

2023-07-14 10:48 UTC, merged